CREATE TABLE `account` (
  `ACCOUNT_ID` varchar(30) NOT NULL,
  `TYPE` varchar(45) NOT NULL,
  `BALANCE` varchar(30) NOT NULL,
  `USER_ID` varchar(30) NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`),
  KEY `USER_ID_idx` (`USER_ID`),
  CONSTRAINT `USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;