CREATE TABLE `DEPARTMENT` (
  `DEPARTMENT_ID` varchar(200) NOT NULL,
  `DEPARTMENT_NAME` varchar(45) NOT NULL,
  
  `MANAGER_ID` varchar(30) NOT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`),
  KEY `Department_idx` (`MANAGER_ID`),
  CONSTRAINT `MANAGER_ID` FOREIGN KEY (`MANAGER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;