CREATE TABLE IF NOT EXISTS `roles` (
  `ROLE_ID` varchar(30) NOT NULL,
  `AUTHORITY` varchar(45) NOT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `AUTHORITY` (`AUTHORITY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
